config/routes.rb
Rails.application.routes.draw do
  get 'graphic/index'

  get 'report/index'

  resources :fields
  resources :events
  resources :event_details
  resources :logs
  match 'app/read', to: 'app#read', as: :read_path, via: [:get, :post]
  match 'app/get_channel', to: 'app#get_channel', as: :get_channel, via: [:get, :post]
  match 'app/write', to: 'app#write', as: :write_path, via: [:get, :post]
  match 'app/get_channel_info', to: 'app#get_channel_info', as: :get_channel_info_path, via: [:get, :post]

  resources :channels
  resources :reports
  get 'home/index', as: :index

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  # Push Notification
  post '/subscribe' => 'subscriptions#create'
  post '/unsubscribe' => 'subscriptions#destroy'

  authenticate :user do
    mount Blazer::Engine, at: "blazer"
  end
end

app/models/channel.rb
# == Schema Information
#
# Table name: channels
#
#  id                  :integer          not null, primary key
#  user_id             :integer
#  name                :string
#  description         :text
#  metadata            :text
#  tags                :text
#  latitude            :string
#  longitude           :string
#  elevation           :string
#  firebase_url        :string
#  firebase_secret_key :string
#  access              :integer
#  send_method         :integer
#  active              :boolean
#  read_api_key        :string
#  write_api_key       :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class Channel < ApplicationRecord
  belongs_to :user, required: true

  enum access: [:public_access, :private_access]
  enum send_method: [:get, :post, :any]

  has_many :fields, inverse_of: :channel
  accepts_nested_attributes_for :fields, reject_if: :all_blank, allow_destroy: true

  validates_presence_of :name, :description, :read_api_key, :write_api_key

  before_validation :create_apis, on: :create

  def create_apis
    self.read_api_key = rand(36**40).to_s(36).upcase
    self.write_api_key = rand(36**40).to_s(36).upcase
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :authenticate_user!

  protect_from_forgery with: :exception
  before_action :set_channel, only: [:show, :edit, :update, :destroy]

  # GET /channels
  # GET /channels.json
  def index
    @channels = current_user.channels
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
  end

  # GET /channels/new
  def new
    @channel = current_user.channels.new
  end

  # GET /channels/1/edit
  def edit
  end

  # POST /channels
  # POST /channels.json
  def create
    @channel = current_user.channels.new(channel_params)

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: 'Channel was successfully created.' }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1
  # PATCH/PUT /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { render :show, status: :ok, location: @channel }
      else
        format.html { render :edit }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url, notice: 'Channel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def channel_params
      params.require(:channel).permit(:user_id, :name, :description, :metadata, :tags, :firebase_url, :firebase_secret_key, :latitude, :longitude, :elevation, :access, :active, :send_method, fields_attributes: [:id, :name, :_destroy])
    end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_field_fields.html.erb
<div class="row">
<div class="nested-fields">
  <%= f.input :name, wrapper_html: {class: 'col-md-10'}, label: 'Field Name' %>
  <%= link_to_remove_association "Remove", f %>
</div>
</div>

app/views/channels/_form.html.erb
<%= simple_form_for(@channel) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="row">
      <div class="col-md-6">
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :firebase_url %>
        <%= f.input :firebase_secret_key %>
        <%= f.input :send_method, collection: Channel.send_methods.keys.map {|w| [w.humanize, w]} %>
        <%= f.input :access, collection: Channel.accesses.keys.map {|w| [w.humanize, w]} %>
        <%= f.input :active %>
      </div>
      <div class="col-md-6">
        <%= f.input :metadata, as: :text, :input_html => {:rows => 3} %>
        <%= f.input :tags, as: :text, :input_html => {:rows => 3} %>
        <%= f.input :latitude %>
        <%= f.input :longitude %>
        <%= f.input :elevation %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">Channel Fields</div>
          <div class="panel-body">
            <div id="fields">
              <%= f.simple_fields_for :fields do |field| %>
                <%= render 'field_fields', f: field %>
              <% end %>
              <%= link_to_add_association 'add field', f, :fields %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/channels/edit.html.erb
<h1>Editing Channel</h1>

<%= render 'form', channel: @channel %>

<%= link_to 'Show', @channel %> |
<%= link_to 'Back', channels_path %>

app/views/channels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Channels</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Access</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @channels.each do |channel| %>
      <tr>
        <td><%= channel.name %></td>
        <td><%= channel.description %></td>
        <td><%= channel.access.to_s.titleize %></td>
        <td><%= channel.active.to_s.titleize %></td>
        <td><%= link_to 'Show', channel %></td>
        <td><%= link_to 'Edit', edit_channel_path(channel) %></td>
        <td><%= link_to 'Destroy', channel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Channel', new_channel_path %>

app/views/channels/new.html.erb
<h1>New Channel</h1>

<%= render 'form', channel: @channel %>

<%= link_to 'Back', channels_path %>

app/views/channels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @channel.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @channel.description %>
</p>

<p>
  <strong>Fields:</strong><br/>
  <div style="margin-left: 70px;">
  <% @channel.fields.uniq.each do |field| %>
  <%= field.name %><br/>
  <% end %>
  </div>
</p>

<p>

<p>
  <strong>Metadata:</strong>
  <%= @channel.metadata %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @channel.tags %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @channel.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @channel.longitude %>
</p>

<p>
  <strong>Elevation:</strong>
  <%= @channel.elevation %>
</p>

<p>
  <strong>Access:</strong>
  <%= @channel.access %>
</p>

<p>
  <strong>Active:</strong>
  <%= @channel.active %>
</p>

<p>
  <strong>Read api key:</strong>
  <%= @channel.read_api_key %>
</p>

<p>
  <strong>Write api key:</strong>
  <%= @channel.write_api_key %>
</p>

<%= link_to 'Edit', edit_channel_path(@channel) %> |
<%= link_to 'Back', channels_path %>