config/routes.rb
Rails.application.routes.draw do
  get 'graphic/index'

  get 'report/index'

  resources :fields
  resources :events
  resources :event_details
  resources :logs
  match 'app/read', to: 'app#read', as: :read_path, via: [:get, :post]
  match 'app/get_channel', to: 'app#get_channel', as: :get_channel, via: [:get, :post]
  match 'app/write', to: 'app#write', as: :write_path, via: [:get, :post]
  match 'app/get_channel_info', to: 'app#get_channel_info', as: :get_channel_info_path, via: [:get, :post]

  resources :channels
  resources :reports
  get 'home/index', as: :index

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  # Push Notification
  post '/subscribe' => 'subscriptions#create'
  post '/unsubscribe' => 'subscriptions#destroy'

  authenticate :user do
    mount Blazer::Engine, at: "blazer"
  end
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id                :integer          not null, primary key
#  name              :string
#  user_id           :integer
#  script            :text
#  message           :string
#  sms               :boolean
#  email             :boolean
#  push_notification :boolean
#  call_back_url     :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Event < ApplicationRecord
  belongs_to :user

  has_many :event_details, inverse_of: :event, dependent: :destroy
  accepts_nested_attributes_for :event_details, reject_if: :all_blank, allow_destroy: true

  has_many :sent_sms_messages, inverse_of: :event, dependent: :destroy
  accepts_nested_attributes_for :sent_sms_messages, reject_if: :all_blank, allow_destroy: true

  has_many :sent_emails, inverse_of: :event, dependent: :destroy
  accepts_nested_attributes_for :sent_emails, reject_if: :all_blank, allow_destroy: true

  has_many :sent_callbacks, inverse_of: :event, dependent: :destroy
  accepts_nested_attributes_for :sent_callbacks, reject_if: :all_blank, allow_destroy: true

    has_many :sent_push_notifications, inverse_of: :event, dependent: :destroy
  accepts_nested_attributes_for :sent_push_notifications, reject_if: :all_blank, allow_destroy: true

  has_many :event_script_fields

  before_validation do
    begin
      # value hariç diğer field lar seçiliyor.
      self.script.scan(/:\w+/).uniq.delete_if {|x| x == ':value' }.each do |field|
        if self.user.fields.where(name: field.gsub(':','')).count == 0
          errors[:script] << "Event script is not valid. Field name: #{field}"
        end
      end
    rescue

    end
  end

  after_save do
    self.event_script_fields.destroy_all
    self.script.scan(/:\w+/).uniq.delete_if {|x| x == ':value' }.each do |field|
      field.slice!(0)
      self.event_script_fields.create!(field_id: Field.joins(:channel).where('channels.user_id = ?', self.user.id).where('fields.name = ?', field).first.id)
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!

  protect_from_forgery with: :exception
  before_action :set_event, only: [:edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = current_user.events.includes(:event_details, :sent_sms_messages, :sent_emails, :sent_callbacks, :sent_push_notifications)
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.includes(:event_details, :sent_sms_messages, :sent_emails, :sent_callbacks, :sent_push_notifications).find(params[:id])
  end

  # GET /events/new
  def new
    @event = current_user.events.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.new(event_params)

    respond_to do |format|
      if @event.save
        FcmTopicsService.new("event_#{@event.id}", session[:subscriber]).create
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:user_id, :script, :message, :sms, :email, :push_notification, :call_back_url,
                                    event_details_attributes: [:id, :field_id, :operation, :value, :_destroy],
                                    sent_sms_messages_attributes: [:id, :phone, :_destroy],
                                    sent_emails_attributes: [:id, :email, :_destroy],
                                    sent_callbacks_attributes: [:id, :callback, :_destroy],
                                    sent_push_notifications_attributes: [:id, :push_notification, :_destroy],
                                    )
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event_detail_fields.html.erb
<div class="row">
  <div class="nested-fields">
    <%= f.association :field, collection:@event.user.fields.pluck('fields.name, fields.id').uniq, wrapper_html: {class: 'col-md-4'} %>
    <%= f.input :operation, as: :select, collection: [['< (Küçüktür)', '<'],
                                                      ['&#8804; (Küçük Eşittir)'.html_safe, '<='],
                                                      ['> (Büyüktür)', '>'],
                                                      ['&#8805; (Büyük Eşittir)'.html_safe, '>='],
                                                      ['= (Eşittir)', '=='],
                                                      ["&ne;  (Eşit Değildir)".html_safe, '!=']],
                wrapper_html: {class: 'col-md-4'} %>
    <%= f.input :value, wrapper_html: {class: 'col-md-2'} %>
    <%= link_to_remove_association "Remove", f %>
  </div>
</div>

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :script %>
    <%= f.input :message, as: :text %>
    <div class="row">
      <div class="col-md-6">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title">Mobile Phones</h3>
          </div>
          <div class="panel-body">
            <div id="event_sms">
              <%= f.simple_fields_for :sent_sms_messages do |sms_message| %>
                <%= render 'sent_sms_message_fields', f: sms_message %>
              <% end %>
              <%= link_to_add_association 'Add Mobil Phone', f, :sent_sms_messages %>
            </div>
          </div>
        </div>

        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title">E-mails</h3>
          </div>
          <div class="panel-body">
              <div id="event_email">
                <%= f.simple_fields_for :sent_emails do |email| %>
                  <%= render 'sent_email_fields', f: email %>
                <% end %>
                <%= link_to_add_association 'Add E-mail Address', f, :sent_emails %>
              </div>
          </div>
        </div>


        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title">Callback URLs</h3>
          </div>
          <div class="panel-body">
              <div id="event_callback">
                <%= f.simple_fields_for :sent_callbacks do |callback| %>
                  <%= render 'sent_callback_fields', f: callback %>
                <% end %>
                <%= link_to_add_association 'Add Callback Url', f, :sent_callbacks %>
              </div>
          </div>
        </div>

        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title">Push Notifications</h3>
          </div>
          <div class="panel-body">
              <div id="event_push_notification">
                <%= f.simple_fields_for :sent_push_notifications do |push_notification| %>
                  <%= render 'sent_push_notification_fields', f: push_notification %>

                <% end %>
                <%= link_to_add_association 'Add Push Notification', f, :sent_push_notifications %>
              </div>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title">Event Details</h3>
          </div>
          <div class="panel-body">
            <div id="event_sms">
              <div id="event_email">

                <div id="event_details">
                  <%= f.simple_fields_for :event_details do |event_detail| %>
                    <%= render 'event_detail_fields', f: event_detail %>
                  <% end %>
                  <%= link_to_add_association 'add event detail', f, :event_details %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  </div>
<% end %>

app/views/events/_sent_callback_fields.html.erb
<div class="nested-fields row">
  <%= f.input :callback, wrapper_html: {class: 'col-md-6'}, label: 'Callback URL' %>
  <%= link_to_remove_association "Remove", f %>
</div>

app/views/events/_sent_email_fields.html.erb
<div class="nested-fields row">
  <%= f.input :email, wrapper_html: {class: 'col-md-6'} %>
  <%= link_to_remove_association "Remove", f %>
</div>

app/views/events/_sent_push_notification_fields.html.erb
<div class="nested-fields row">
  <%= f.input :push_notification, wrapper_html: {class: 'col-md-6'} %>
  <%= link_to_remove_association "Remove", f %>
</div>

app/views/events/_sent_sms_message_fields.html.erb
<div class="nested-fields row">
  <%= f.input :phone, wrapper_html: {class: 'col-md-6'} %>
  <%= link_to_remove_association "Remove", f %>
</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Message</th>
      <th>Sms</th>
      <th>Email</th>
      <th>Push notification</th>
      <th>Call back url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.message %></td>
        <td>
          <% event.sent_sms_messages.each do |sent_sms| %>
            <%= sent_sms.phone %><br/>
          <% end %>
        </td>
        <td>
          <% event.sent_emails.each do |email| %>
            <%= email.email %><br/>
          <% end %>
        </td>
        <td><%= event.push_notification %></td>
        <td>
          <% event.sent_callbacks.each do |callback| %>
            <%= callback.callback %><br/>
          <% end %>
        </td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @event.user.email %>
</p>

<p>
  <strong>Script:</strong>
  <%= @event.script %>
</p>

<p>
  <strong>Message:</strong>
  <%= @event.message %>
</p>

<p>
  <strong>Sms:</strong>
  <% @event.sent_sms_messages.each do |sent_sms| %>
   <%= sent_sms.phone %><br/>
  <% end %>
</p>

<p>
  <strong>Email:</strong>
  <% @event.sent_emails.each do |email| %>
    <%= email.email %><br/>
  <% end %>
</p>

<p>
  <strong>Push notification:</strong>
  <%= @event.push_notification %><br/>
</p>

<p>
  <strong>Call back url:</strong>
  <% @event.sent_callbacks.each do |callback| %>
    <%= callback.callback %><br/>
  <% end %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>