config/routes.rb
Rails.application.routes.draw do
  get 'graphic/index'

  get 'report/index'

  resources :fields
  resources :events
  resources :event_details
  resources :logs
  match 'app/read', to: 'app#read', as: :read_path, via: [:get, :post]
  match 'app/get_channel', to: 'app#get_channel', as: :get_channel, via: [:get, :post]
  match 'app/write', to: 'app#write', as: :write_path, via: [:get, :post]
  match 'app/get_channel_info', to: 'app#get_channel_info', as: :get_channel_info_path, via: [:get, :post]

  resources :channels
  resources :reports
  get 'home/index', as: :index

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  # Push Notification
  post '/subscribe' => 'subscriptions#create'
  post '/unsubscribe' => 'subscriptions#destroy'

  authenticate :user do
    mount Blazer::Engine, at: "blazer"
  end
end

app/models/log.rb
# == Schema Information
#
# Table name: logs
#
#  id         :integer          not null, primary key
#  field_id   :integer
#  value      :decimal(, )
#  ip_address :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Log < ApplicationRecord
  belongs_to :field

  after_save do
    EventControlJob.perform_later(field_id, value)
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :authenticate_user!

  protect_from_forgery with: :exception
  before_action :set_log, only: [:show, :edit, :update, :destroy]

  # GET /logs
  # GET /logs.json
  def index
    @logs = Log.all
  end

  # GET /logs/1
  # GET /logs/1.json
  def show
  end

  # GET /logs/new
  def new
    @log = Log.new
  end

  # GET /logs/1/edit
  def edit
  end

  # POST /logs
  # POST /logs.json
  def create
    @log = Log.new(log_params)

    respond_to do |format|
      if @log.save
        format.html { redirect_to @log, notice: 'Log was successfully created.' }
        format.json { render :show, status: :created, location: @log }
      else
        format.html { render :new }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logs/1
  # PATCH/PUT /logs/1.json
  def update
    respond_to do |format|
      if @log.update(log_params)
        format.html { redirect_to @log, notice: 'Log was successfully updated.' }
        format.json { render :show, status: :ok, location: @log }
      else
        format.html { render :edit }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1
  # DELETE /logs/1.json
  def destroy
    @log.destroy
    respond_to do |format|
      format.html { redirect_to logs_url, notice: 'Log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log
      @log = Log.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def log_params
      params.require(:log).permit(:channel, :field_1, :field_2, :field_3, :field_4, :field_5, :field_6, :field_7, :field_8, :field_9, :field_10, :latitude, :longitude, :elevation)
    end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/_form.html.erb
<%= simple_form_for(@log) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :channel %>
    <%= f.input :field_1 %>
    <%= f.input :field_2 %>
    <%= f.input :field_3 %>
    <%= f.input :field_4 %>
    <%= f.input :field_5 %>
    <%= f.input :field_6 %>
    <%= f.input :field_7 %>
    <%= f.input :field_8 %>
    <%= f.input :field_9 %>
    <%= f.input :field_10 %>
    <%= f.input :latitude %>
    <%= f.input :longitude %>
    <%= f.input :elevation %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/logs/edit.html.erb
<h1>Editing Log</h1>

<%= render 'form', log: @log %>

<%= link_to 'Show', @log %> |
<%= link_to 'Back', logs_path %>

app/views/logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Logs</h1>

<table>
  <thead>
    <tr>
      <th>Channel</th>
      <th>Field 1</th>
      <th>Field 2</th>
      <th>Field 3</th>
      <th>Field 4</th>
      <th>Field 5</th>
      <th>Field 6</th>
      <th>Field 7</th>
      <th>Field 8</th>
      <th>Field 9</th>
      <th>Field 10</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Elevation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logs.each do |log| %>
      <tr>
        <td><%= log.channel %></td>
        <td><%= log.field_1 %></td>
        <td><%= log.field_2 %></td>
        <td><%= log.field_3 %></td>
        <td><%= log.field_4 %></td>
        <td><%= log.field_5 %></td>
        <td><%= log.field_6 %></td>
        <td><%= log.field_7 %></td>
        <td><%= log.field_8 %></td>
        <td><%= log.field_9 %></td>
        <td><%= log.field_10 %></td>
        <td><%= log.latitude %></td>
        <td><%= log.longitude %></td>
        <td><%= log.elevation %></td>
        <td><%= link_to 'Show', log %></td>
        <td><%= link_to 'Edit', edit_log_path(log) %></td>
        <td><%= link_to 'Destroy', log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Log', new_log_path %>

app/views/logs/new.html.erb
<h1>New Log</h1>

<%= render 'form', log: @log %>

<%= link_to 'Back', logs_path %>

app/views/logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Channel:</strong>
  <%= @log.channel %>
</p>

<p>
  <strong>Field 1:</strong>
  <%= @log.field_1 %>
</p>

<p>
  <strong>Field 2:</strong>
  <%= @log.field_2 %>
</p>

<p>
  <strong>Field 3:</strong>
  <%= @log.field_3 %>
</p>

<p>
  <strong>Field 4:</strong>
  <%= @log.field_4 %>
</p>

<p>
  <strong>Field 5:</strong>
  <%= @log.field_5 %>
</p>

<p>
  <strong>Field 6:</strong>
  <%= @log.field_6 %>
</p>

<p>
  <strong>Field 7:</strong>
  <%= @log.field_7 %>
</p>

<p>
  <strong>Field 8:</strong>
  <%= @log.field_8 %>
</p>

<p>
  <strong>Field 9:</strong>
  <%= @log.field_9 %>
</p>

<p>
  <strong>Field 10:</strong>
  <%= @log.field_10 %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @log.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @log.longitude %>
</p>

<p>
  <strong>Elevation:</strong>
  <%= @log.elevation %>
</p>

<%= link_to 'Edit', edit_log_path(@log) %> |
<%= link_to 'Back', logs_path %>