config/routes.rb
Rails.application.routes.draw do
  get 'graphic/index'

  get 'report/index'

  resources :fields
  resources :events
  resources :event_details
  resources :logs
  match 'app/read', to: 'app#read', as: :read_path, via: [:get, :post]
  match 'app/get_channel', to: 'app#get_channel', as: :get_channel, via: [:get, :post]
  match 'app/write', to: 'app#write', as: :write_path, via: [:get, :post]
  match 'app/get_channel_info', to: 'app#get_channel_info', as: :get_channel_info_path, via: [:get, :post]

  resources :channels
  resources :reports
  get 'home/index', as: :index

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  # Push Notification
  post '/subscribe' => 'subscriptions#create'
  post '/unsubscribe' => 'subscriptions#destroy'

  authenticate :user do
    mount Blazer::Engine, at: "blazer"
  end
end

app/models/field.rb
# == Schema Information
#
# Table name: fields
#
#  id         :integer          not null, primary key
#  channel_id :integer
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Field < ApplicationRecord
  belongs_to :channel
  has_many :field_values
  has_many :logs

  before_save do
    self.name = self.name.parameterize
  end

  # default_scope { left_joins(:logs) }

  scope :logs, -> { left_joins(:logs) }
  scope :query, ->(name) { where(name: name) }
  scope :date, ->(symbol, date) { where("logs.created_at #{symbol} '#{date}'")}
  scope :between_date, ->(date1, date2) { where(created_at: date1..date2)}
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  before_action :authenticate_user!

  protect_from_forgery with: :exception
  before_action :set_field, only: [:show, :edit, :update, :destroy]

  # GET /fields
  # GET /fields.json
  def index
    @fields = Field.all
  end

  # GET /fields/1
  # GET /fields/1.json
  def show
  end

  # GET /fields/new
  def new
    @field = Field.new
  end

  # GET /fields/1/edit
  def edit
  end

  # POST /fields
  # POST /fields.json
  def create
    @field = Field.new(field_params)

    respond_to do |format|
      if @field.save
        format.html { redirect_to @field, notice: 'Field was successfully created.' }
        format.json { render :show, status: :created, location: @field }
      else
        format.html { render :new }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fields/1
  # PATCH/PUT /fields/1.json
  def update
    respond_to do |format|
      if @field.update(field_params)
        format.html { redirect_to @field, notice: 'Field was successfully updated.' }
        format.json { render :show, status: :ok, location: @field }
      else
        format.html { render :edit }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fields/1
  # DELETE /fields/1.json
  def destroy
    @field.destroy
    respond_to do |format|
      format.html { redirect_to fields_url, notice: 'Field was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_field
      @field = Field.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def field_params
      params.require(:field).permit(:channel_id, :name, :type)
    end
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/views/fields/_form.html.erb
<%= simple_form_for(@field) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :channel %>
    <%= f.input :name %>
    <%= f.input :type %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/fields/edit.html.erb
<h1>Editing Field</h1>

<%= render 'form', field: @field %>

<%= link_to 'Show', @field %> |
<%= link_to 'Back', fields_path %>

app/views/fields/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fields</h1>

<table>
  <thead>
    <tr>
      <th>Channel</th>
      <th>Name</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fields.each do |field| %>
      <tr>
        <td><%= field.channel %></td>
        <td><%= field.name %></td>
        <td><%= field.type %></td>
        <td><%= link_to 'Show', field %></td>
        <td><%= link_to 'Edit', edit_field_path(field) %></td>
        <td><%= link_to 'Destroy', field, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Field', new_field_path %>

app/views/fields/new.html.erb
<h1>New Field</h1>

<%= render 'form', field: @field %>

<%= link_to 'Back', fields_path %>

app/views/fields/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Channel:</strong>
  <%= @field.channel %>
</p>

<p>
  <strong>Name:</strong>
  <%= @field.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @field.type %>
</p>

<%= link_to 'Edit', edit_field_path(@field) %> |
<%= link_to 'Back', fields_path %>